run:
  timeout: 10m
linters:
  disable-all: true
  enable:
    - deadcode
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - structcheck
    - typecheck
    - unused
    - varcheck
    - asciicheck
    - bidichk
    - bodyclose
    - contextcheck
    - cyclop
    - durationcheck
    - errname
    - errorlint
    - exhaustive
    - exportloopref
    - funlen
    - forbidigo
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - goimports
    - gomodguard
    - goprintffuncname
    - gosec
    - lll
    - makezero
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - promlinter
    - revive
    - rowserrcheck
    - sqlclosecheck
    - stylecheck
    - tenv
    - tparallel
    - unconvert
    - unparam
    - wastedassign
    - whitespace

linters-settings:
  cyclop:
    max-complexity: 20
    skip-tests: true
  funlen:
    lines: 78
    statements: 65
  lll:
    line-length: 225
output:
  uniq-by-line: false

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    - source: "^//\\s*go:generate\\s"
      linters:
        - lll
    - source: "//noinspection"
      linters:
        - gocritic
    - source: "^\\s+if _, ok := err\\.\\([^.]+\\.InternalError\\); ok {"
      linters:
        - errorlint
    - path: "_test\\.go"
      linters:
        - bodyclose
        - deadcode
        - funlen
        - goconst
        - noctx
        - unused
        - varcheck
        - wrapcheck
        - lll
